layer.translucent= minecraft:glass_pane minecraft:glass


### LIGHTS ###

#= BLOCK_LIGHT_1
block.10=light:level=1

#= BLOCK_LIGHT_2
block.*=light:level=2

#= BLOCK_LIGHT_3
block.*=light:level=3

#= BLOCK_LIGHT_4
block.*=light:level=4

#= BLOCK_LIGHT_5
block.*=light:level=5

#= BLOCK_LIGHT_6
block.*=light:level=6

#= BLOCK_LIGHT_7
block.*=light:level=7

#= BLOCK_LIGHT_8
block.*=light:level=8

#= BLOCK_LIGHT_9
block.*=light:level=9

#= BLOCK_LIGHT_10
block.*=light:level=10

#= BLOCK_LIGHT_11
block.*=light:level=11

#= BLOCK_LIGHT_12
block.*=light:level=12

#= BLOCK_LIGHT_13
block.*=light:level=13

#= BLOCK_LIGHT_14
block.*=light:level=14

#= BLOCK_LIGHT_15
block.*=light:level=15

#= BLOCK_AMETHYST_BUD_LARGE
block.*=large_amethyst_bud

#= BLOCK_AMETHYST_BUD_MEDIUM
block.*=medium_amethyst_bud

#= BLOCK_AMETHYST_BUD_SMALL
block.*=small_amethyst_bud

#= BLOCK_AMETHYST_CLUSTER
block.*=amethyst_cluster

#= BLOCK_BEACON
block.*=beacon

#= BLOCK_BLAST_FURNACE_LIT
block.*=blast_furnace:lit=true

#= BLOCK_BREWING_STAND
block.*=brewing_stand

#= BLOCK_CAMPFIRE_LIT
block.*=campfire:lit=true

#= BLOCK_CAVEVINE_BERRIES
block.*=cave_vines:berries=true cave_vines_plant:berries=true

#= BLOCK_COPPER_BULB_LIT
block.*=copper_bulb:lit=true waxed_copper_bulb:lit=true

#= BLOCK_COPPER_BULB_EXPOSED_LIT
block.*=exposed_copper_bulb:lit=true waxed_exposed_copper_bulb:lit=true

#= BLOCK_COPPER_BULB_WEATHERED_LIT
block.*=weathered_copper_bulb:lit=true waxed_weathered_copper_bulb:lit=true

#= BLOCK_COPPER_BULB_OXIDIZED_LIT
block.*=oxidized_copper_bulb:lit=true waxed_oxidized_copper_bulb:lit=true

#= BLOCK_COPPER_LANTERN
block.*=minecraft:copper_lantern waxed_copper_lantern

#= BLOCK_COPPER_TORCH
block.*=copper_torch copper_wall_torch

#= BLOCK_CRYING_OBSIDIAN
block.*=crying_obsidian

#= BLOCK_END_ROD
block.*=end_rod

#= BLOCK_FIRE
block.*=fire

#= BLOCK_FROGLIGHT_OCHRE
block.*=ochre_froglight

#= BLOCK_FROGLIGHT_PEARLESCENT
block.*=pearlescent_froglight

#= BLOCK_FROGLIGHT_VERDANT
block.*=verdant_froglight

#= BLOCK_FURNACE_LIT
block.*=furnace:lit=true

#= BLOCK_GLOWSTONE
block.*=glowstone

#= BLOCK_GLOW_LICHEN
block.*=glow_lichen

#= BLOCK_JACK_O_LANTERN
block.*=jack_o_lantern

#= BLOCK_LANTERN
block.*=lantern

#= BLOCK_LAVA
block.*=lava

#= BLOCK_LIGHTING_ROD_POWERED
block.*=lightning_rod:powered=true

#= BLOCK_MAGMA
block.*=magma_block

#= BLOCK_NETHER_PORTAL
block.*=nether_portal

#= BLOCK_OXIDIZED_COPPER_LANTERN
block.*=oxidized_copper_lantern waxed_oxidized_copper_lantern

#= BLOCK_REDSTONE_LAMP_LIT
block.*=redstone_lamp:lit=true

#= BLOCK_REDSTONE_ORE_LIT
block.*=redstone_ore:lit=true deepslate_redstone_ore:lit=true

#= BLOCK_REDSTONE_TORCH_LIT
block.*=redstone_torch:lit=true redstone_wall_torch:lit=true

#= BLOCK_RESPAWN_ANCHOR_4
block.*=respawn_anchor:charges=4

#= BLOCK_RESPAWN_ANCHOR_3
block.*=respawn_anchor:charges=3

#= BLOCK_RESPAWN_ANCHOR_2
block.*=respawn_anchor:charges=2

#= BLOCK_RESPAWN_ANCHOR_1
block.*=respawn_anchor:charges=1

#= BLOCK_SCULK_CATALYST
block.*=sculk_catalyst

#= BLOCK_SEA_LANTERN
block.*=sea_lantern ae2:quartz_fixture

#= BLOCK_SEA_PICKLE_WET_1
block.*=sea_pickle:waterlogged=true:pickles=1

#= BLOCK_SEA_PICKLE_WET_2
block.*=sea_pickle:waterlogged=true:pickles=2

#= BLOCK_SEA_PICKLE_WET_3
block.*=sea_pickle:waterlogged=true:pickles=3

#= BLOCK_SEA_PICKLE_WET_4
block.*=sea_pickle:waterlogged=true:pickles=4

#= BLOCK_SHROOMLIGHT
block.*=shroomlight

#= BLOCK_SMOKER_LIT
block.*=smoker:lit=true

#= BLOCK_SOUL_CAMPFIRE_LIT
block.*=soul_campfire:lit=true

#= BLOCK_SOUL_FIRE
block.*=soul_fire

#= BLOCK_SOUL_LANTERN
block.*=soul_lantern \
		supplementaries:wall_lantern:light_level=10

#= BLOCK_SOUL_TORCH
block.*=soul_torch soul_wall_torch

#= BLOCK_TORCH
block.*=torch wall_torch

#= BLOCK_WEATHERED_COPPER_LANTERN
block.*=weathered_copper_lantern waxed_weathered_copper_lantern


### TINTED ###

#= BLOCK_HONEY
block.*=honey_block

#= BLOCK_SLIME
block.*=slime_block

#= BLOCK_STAINED_GLASS_BLACK
block.*=black_stained_glass black_stained_glass_pane

#= BLOCK_STAINED_GLASS_BLUE
block.*=blue_stained_glass blue_stained_glass_pane

#= BLOCK_STAINED_GLASS_BROWN
block.*=brown_stained_glass brown_stained_glass_pane

#= BLOCK_STAINED_GLASS_CYAN
block.*=cyan_stained_glass cyan_stained_glass_pane

#= BLOCK_STAINED_GLASS_GRAY
block.*=gray_stained_glass gray_stained_glass_pane

#= BLOCK_STAINED_GLASS_GREEN
block.*=green_stained_glass green_stained_glass_pane

#= BLOCK_STAINED_GLASS_LIGHT_BLUE
block.*=light_blue_stained_glass light_blue_stained_glass_pane

#= BLOCK_STAINED_GLASS_LIGHT_GRAY
block.*=light_gray_stained_glass light_gray_stained_glass_pane

#= BLOCK_STAINED_GLASS_LIME
block.*=lime_stained_glass lime_stained_glass_pane

#= BLOCK_STAINED_GLASS_MAGENTA
block.*=magenta_stained_glass magenta_stained_glass_pane

#= BLOCK_STAINED_GLASS_ORANGE
block.*=orange_stained_glass orange_stained_glass_pane

#= BLOCK_STAINED_GLASS_PINK
block.*=pink_stained_glass pink_stained_glass_pane

#= BLOCK_STAINED_GLASS_PURPLE
block.*=purple_stained_glass purple_stained_glass_pane

#= BLOCK_STAINED_GLASS_RED
block.*=red_stained_glass red_stained_glass_pane

#= BLOCK_STAINED_GLASS_WHITE
block.*=white_stained_glass white_stained_glass_pane

#= BLOCK_STAINED_GLASS_YELLOW
block.*=yellow_stained_glass yellow_stained_glass_pane

#= BLOCK_TINTED_GLASS
block.*=tinted_glass


### OTHER ###

#= BLOCK_GLASS
block.*= minecraft:glass minecraft:glass_pane

# wavy plants, translucent, bottom vertices not moving
#= BLOCK_PLANT_WAVING_TOP
block.*= minecraft:wheat minecraft:beetroots minecraft:potatoes minecraft:carrots minecraft:oxeye_daisy minecraft:pink_tulip minecraft:white_tulip minecraft:orange_tulip minecraft:red_tulip minecraft:azure_bluet minecraft:allium minecraft:blue_orchid minecraft:poppy minecraft:dandelion minecraft:grass minecraft:short_grass minecraft:dead_bush minecraft:fern minecraft:oak_sapling minecraft:spruce_sapling minecraft:birch_sapling minecraft:jungle_sapling minecraft:acacia_sapling minecraft:dark_oak_sapling

# wavy plants (blocks)
#= BLOCK_PLANT_WAVING_FULL
block.*= minecraft:vine minecraft:oak_leaves minecraft:spruce_leaves minecraft:birch_leaves minecraft:jungle_leaves minecraft:acacia_leaves minecraft:dark_oak_leaves

#= BLOCK_IDK
block.*= minecraft:slime minecraft:grass_block:snowy=true minecraft:packed_ice minecraft:snow minecraft:horn_coral_wall_fan minecraft:fire_coral_wall_fan minecraft:bubble_coral_wall_fan minecraft:brain_coral_wall_fan minecraft:tube_coral_wall_fan minecraft:frosted_ice minecraft:blue_ice minecraft:dead_horn_coral_fan minecraft:dead_fire_coral_fan minecraft:dead_bubble_coral_fan minecraft:dead_brain_coral_fan minecraft:dead_tube_coral_fan minecraft:horn_coral_fan minecraft:fire_coral_fan minecraft:bubble_coral_fan minecraft:brain_coral_fan minecraft:tube_coral_fan minecraft:dead_tube_coral minecraft:dead_horn_coral minecraft:dead_fire_coral minecraft:dead_bubble_coral minecraft:dead_brain_coral minecraft:horn_coral minecraft:fire_coral minecraft:bubble_coral minecraft:brain_coral minecraft:tube_coral minecraft:sea_pickle minecraft:brown_mushroom minecraft:red_mushroom minecraft:melon minecraft:pumpkin minecraft:carved_pumpkin minecraft:snow_block minecraft:cactus minecraft:sugar_cane

# translucent
#= BLOCK_SSS
block.*= minecraft:tall_seagrass minecraft:lily_of_the_valley minecraft:cornflower minecraft:kelp_plant minecraft:tripwire minecraft:melon_stem minecraft:pumpkin_stem minecraft:attached_melon_stem minecraft:attached_pumpkin_stem   minecraft:large_fern minecraft:tall_grass minecraft:peony minecraft:rose_bush minecraft:lilac minecraft:sunflower minecraft:lily_pad minecraft:cobweb minecraft:seagrass

# reflective surfaces (not including water and ice)
#= BLOCK_REFLECTIVE
block.*= minecraft:black_stained_glass minecraft:black_stained_glass_pane minecraft:blue_stained_glass minecraft:blue_stained_glass_pane  minecraft:brown_stained_glass minecraft:brown_stained_glass_pane minecraft:cyan_stained_glass minecraft:cyan_stained_glass_pane  minecraft:gray_stained_glass minecraft:gray_stained_glass_pane minecraft:green_stained_glass minecraft:green_stained_glass_pane minecraft:light_blue_stained_glass minecraft:light_blue_stained_glass_pane minecraft:light_gray_stained_glass minecraft:light_gray_stained_glass_pane minecraft:lime_stained_glass minecraft:lime_stained_glass_pane minecraft:magenta_stained_glass minecraft:magenta_stained_glass_pane minecraft:orange_stained_glass minecraft:orange_stained_glass_pane minecraft:pink_stained_glass minecraft:pink_stained_glass_pane minecraft:purple_stained_glass minecraft:purple_stained_glass_pane minecraft:red_stained_glass minecraft:red_stained_glass_pane minecraft:white_stained_glass minecraft:white_stained_glass_pane minecraft:yellow_stained_glass minecraft:yellow_stained_glass_pane minecraft:glass_pane minecraft:glass

#= BLOCK_WATER
block.*= minecraft:water minecraft:flowing_water

#= BLOCK_ICE
block.*= minecraft:ice

#= BLOCK_EMISSIVE
block.*= minecraft:glowstone minecraft:torch minecraft:wall_torch minecraft:lava minecraft:fire minecraft:redstone_torch minecraft:redstone_wall_torch minecraft:jack_o_lantern minecraft:magma_block minecraft:redstone_lamp:lit=true  minecraft:lantern minecraft:campfire:lit=true minecraft:shroomlight minecraft:nether_portal minecraft:soul_torch minecraft:soul_wall_torch minecraft:soul_fire minecraft:copper_torch minecraft:copper_wall_torch minecraft:end_rod minecraft:sea_lantern minecraft:soul_lantern minecraft:end_gateway minecraft:soul_campfire:lit=true minecraft:beacon minecraft:copper_bulb:lit=true minecraft:exposed_copper_bulb:lit=true minecraft:weathered_copper_bulb:lit=true minecraft:oxidixed_copper_bulb:lit=true

#= BLOCK_BANNER
block.*= minecraft:white_wall_banner minecraft:orange_wall_banner minecraft:magenta_wall_banner minecraft:light_blue_wall_banner minecraft:yellow_wall_banner minecraft:lime_wall_banner minecraft:pink_wall_banner minecraft:gray_wall_banner minecraft:light_gray_wall_banner minecraft:cyan_wall_banner minecraft:purple_wall_banner minecraft:blue_wall_banner minecraft:brown_wall_banner minecraft:green_wall_banner minecraft:red_wall_banner minecraft:black_wall_banner minecraft:white_banner minecraft:orange_banner minecraft:magenta_banner minecraft:light_blue_banner minecraft:yellow_banner minecraft:lime_banner minecraft:pink_banner minecraft:gray_banner minecraft:light_gray_banner minecraft:cyan_banner minecraft:purple_banner minecraft:blue_banner minecraft:brown_banner minecraft:green_banner minecraft:red_banner minecraft:black_banner

#= BLOCK_IGNORED
block.*= minecraft:lever \
         %minecraft:buttons %minecraft:doors %minecraft:fences %minecraft:pressure_plates %minecraft:rails %minecraft:trapdoors %minecraft:wool_carpets
