### BLOCKS ###

#= ITEM_AMETHYST_BUD_LARGE
item.BLOCK_AMETHYST_BUD_LARGE=large_amethyst_bud

#= ITEM_AMETHYST_BUD_MEDIUM
item.BLOCK_AMETHYST_BUD_MEDIUM=medium_amethyst_bud

#= ITEM_AMETHYST_BUD_SMALL
item.BLOCK_AMETHYST_BUD_SMALL=small_amethyst_bud

#= ITEM_AMETHYST_CLUSTER
item.BLOCK_AMETHYST_CLUSTER=amethyst_cluster

#= ITEM_BEACON
item.BLOCK_BEACON=beacon

#= ITEM_COPPER_TORCH
item.BLOCK_COPPER_TORCH=copper_torch

#= ITEM_CRYING_OBSIDIAN
item.BLOCK_CRYING_OBSIDIAN=crying_obsidian

#= ITEM_END_ROD
item.BLOCK_END_ROD=end_rod

#= ITEM_FROGLIGHT_OCHRE
item.BLOCK_FROGLIGHT_OCHRE=ochre_froglight

#= ITEM_FROGLIGHT_PEARLESCENT
item.BLOCK_FROGLIGHT_PEARLESCENT=pearlescent_froglight

#= ITEM_FROGLIGHT_VERDANT
item.BLOCK_FROGLIGHT_VERDANT=verdant_froglight

#= ITEM_GLOW_BERRIES
item.BLOCK_CAVEVINE_BERRIES=glow_berries

#= ITEM_GLOW_LICHEN
item.BLOCK_GLOW_LICHEN=glow_lichen

#= ITEM_GLOWSTONE
item.BLOCK_GLOWSTONE=glowstone

#= ITEM_JACK_O_LANTERN
item.BLOCK_JACK_O_LANTERN=jack_o_lantern

#= ITEM_LANTERN
item.BLOCK_LANTERN=lantern

#= ITEM_LIGHT
item.BLOCK_LIGHT_15=light

#= ITEM_MAGMA
item.BLOCK_MAGMA=magma_block

#= ITEM_REDSTONE_TORCH
item.BLOCK_REDSTONE_TORCH_LIT=redstone_torch

#= ITEM_SCULK_CATALYST
item.BLOCK_SCULK_CATALYST=sculk_catalyst

#= ITEM_SEA_LANTERN
item.BLOCK_SEA_LANTERN=sea_lantern

#= ITEM_SHROOMLIGHT
item.BLOCK_SHROOMLIGHT=shroomlight

#= ITEM_SOUL_LANTERN
item.BLOCK_SOUL_LANTERN=soul_lantern

#= ITEM_SOUL_TORCH
item.BLOCK_SOUL_TORCH=soul_torch

#= ITEM_TORCH
item.BLOCK_TORCH=torch


### ITEMS ###

#= ITEM_BLAZE_ROD
item.1000=blaze_rod

#= ITEM_GLOWSTONE_DUST
item.*=glowstone_dust
