colortex0   = low res clouds (deferred->composite2) / low res VL (composite5->composite15)
colortex1   = terrain gbuffer (gbuffer->composite2)
colortex2   = forward + transparencies (gbuffer->composite4)
colortex3   = frame buffer + bloom (deferred6->final)
colortex4   = light values and skyboxes (everything)
colortex5   = TAA buffer (everything)
colortex6   = additionnal buffer for bloom (composite3->final)
colortex7   = transparencies id (gbuffer->composite4) / DOF

colortex8   = gbuffer albedo
colortex9   = gbuffer normals
colortex10  = gbuffer specular [rough, f0, sss, emissive]
colortex11  = gbuffer world [lightmap, id]

colortex13  = rough reflect trace
colortex14  = rough reflect history
