deferred		= prepare sky
deferred1		= clouds
deferred2		= linear Z?

composite		= shadows
composite2		= sky, clouds, terrain
composite5		= VL trace
composite6		= VL upscale
composite7		= TAA min/max
composite8		= TAA resolve
composite9		= bloom down 1
composite10		= bloom down 2
composite11		= bloom blur H
composite12		= bloom blur V
composite14		= bloom up 2
composite15		= bloom up 1/+composite, vignette, tonemap, exposure

final			= CAS, dither
