begin1          = scene
begin2          = forward lightmap
begin3          = deferred lightmap
begin4          = sky gradient
begin5          = sky gradient clouds

deferred1		= scene uniforms
deferred2		= prepare sky
deferred3		= clouds
deferred4		= linear Z?

composite		= shadows
composite2		= sky, clouds, terrain
composite5		= VL trace
composite6		= VL upscale
composite7		= TAA min/max
composite8		= TAA resolve
composite9		= bloom down 1
composite10		= bloom down 2
composite11		= bloom blur H
composite12		= bloom blur V
composite14		= bloom up 2
composite15		= bloom up 1/+composite, vignette, tonemap, exposure

final			= CAS, dither
