setup1			= block light LUT

prepare1		= prepare sky
prepare2		= clear voxel depth

shadowcomp      = floodfill

deferred1     = 3D blocks

deferred2		= clouds
deferred3		= linear Z
deferred4       = center-depth
deferred5       = voxy merged-depth opaque

composite1      = voxy merged-depth translucent
composite2		= shadows
composite3		= sky, clouds, terrain
composite4      = PH WSR trace
composite5      = PH WSR accumulate
composite6		= VL trace
composite7		= VL upscale, composite translucent
composite8		= TAA min/max
composite9		= TAA resolve
composite10		= bloom down 1
composite11		= bloom down 2
composite12		= bloom blur H
composite13		= bloom blur V
composite15		= bloom up 2
composite16		= bloom up 1/+DOF, vignette, tonemap, exposure

final			= CAS, dither
