### BLOCKS ###

item.25=large_amethyst_bud

item.26=medium_amethyst_bud

item.27=small_amethyst_bud

item.28=amethyst_cluster

item.29=beacon

item.39=copper_torch

item.40=crying_obsidian

item.41=end_rod

item.43=ochre_froglight

item.44=pearlescent_froglight

item.45=verdant_froglight

item.33=glow_berries

item.48=glow_lichen

item.47=glowstone

item.49=jack_o_lantern

item.50=lantern

item.24=light

item.53=magma_block

item.58=redstone_torch

item.63=sculk_catalyst

item.64=sea_lantern

item.69=shroomlight

item.73=soul_lantern

item.74=soul_torch

item.75=torch


### ITEMS ###

item.1000=blaze_rod

item.1001=glowstone_dust
