iris.features.required=CUSTOM_IMAGES COMPUTE_SHADERS SEPARATE_HARDWARE_SAMPLERS
iris.features.optional=REVERSED_CULLING ENTITY_TRANSLUCENT

underwaterOverlay=false
dynamicHandLight=false
oldLighting=false
separateAo=true
vignette=false
sun=false
moon=true
stars=false
clouds=off
rain.depth=false
beacon.beam.depth=true

#if defined(PHOTONICS) && defined(PHOTONICS_REFLECT_ENABLED)
    shadow.culling=reversed
#endif

photonics.lightingMode=restir
photonics.maxGiBounces=PHOTONICS_GI_BOUNCES

#if defined(PHOTONICS_BLOCK_LIGHT_ENABLED) || defined(PHOTONICS_HAND_LIGHT_ENABLED) || defined(PHOTONICS_GI_ENABLED) || defined(PHOTONICS_REFLECT_ENABLED)
    photonics.enabled=true
#endif

#if !defined(PHOTONICS_BLOCK_LIGHT_ENABLED) && !defined(PHOTONICS_GI_ENABLED)
    photonics.enableBlockLight=false
#endif

#ifndef PHOTONICS_HAND_LIGHT_ENABLED
    photonics.enableHandheldLight=false
#endif

#ifdef PHOTONICS_GI_ENABLED
    photonics.restirCombinedGi=true

    #ifdef PHOTONICS_GI_BLOCK
        photonics.enableBlockLightGi=true
    #endif
#else
    photonics.enableGi=false
#endif

#if PHOTONICS_TINTING == 2
    photonics.alphaMode=voxel
#elif PHOTONICS_TINTING == 1
    photonics.alphaMode=block
#else
    photonics.alphaMode=none
#endif

#if TAA_RENDER_SCALE != 100
    #if   TAA_RENDER_SCALE == 50
        photonics.renderScale=0.5
    #elif TAA_RENDER_SCALE == 60
        photonics.renderScale=0.6
    #elif TAA_RENDER_SCALE == 70
        photonics.renderScale=0.7
    #elif TAA_RENDER_SCALE == 80
        photonics.renderScale=0.8
    #elif TAA_RENDER_SCALE == 90
        photonics.renderScale=0.9
    #endif
#endif


screen=\
    [CHOCAPIC] [PHOTONICS] \
    <empty> <empty> \
    [Atmospherics] [MATERIALS] \
    [Shadows] [Lighting] \
    [Shading] [Wavy_stuff] \
    [Water_and_transparencies] [Camera] \
    [REFLECTIONS] [TAA_OPTIONS]


screen.CHOCAPIC=\
    DEBUG_WHITEWORLD


screen.PHOTONICS=\
    PHOTONICS_BLOCK_LIGHT_ENABLED [PHOTONICS_REFLECTIONS] \
    PHOTONICS_HAND_LIGHT_ENABLED [PHOTONICS_GI] \
    PHOTONICS_TINTING

screen.PHOTONICS_REFLECTIONS=\
    PHOTONICS_REFLECT_ENABLED PHOTONICS_REFLECT_BOUNCES \
    <empty> PHOTONICS_REFLECT_STEPS

screen.PHOTONICS_GI=\
    PHOTONICS_GI_ENABLED PHOTONICS_GI_BOUNCES \
    PHOTONICS_GI_BLOCK PHOTONICS_GI_STEPS


screen.Atmospherics=\
    SEA_LEVEL VL_SAMPLES \
    [Clouds] [Fog_Color] \
    [Fog_Densities] BLOOMY_FOG \
    VL_RENDER_RESOLUTION VL_Clouds_Shadows

screen.Clouds=\
    VOLUMETRIC_CLOUDS CLOUDS_QUALITY \
    cloud_LevelOfDetail cloud_ShadowLevelOfDetail \
    cloud_LevelOfDetailLQ cloud_ShadowLevelOfDetailLQ \
    minRayMarchSteps maxRayMarchSteps \
    minRayMarchStepsLQ maxRayMarchStepsLQ \
    cloudDensity cloudCoverage \
    fbmAmount fbmPower1 \
    fbmPower2 cloudMieG \
    cloudMieG2 cloudMie2Multiplier

screen.Fog_Color=\
    fog_mieg1 fog_mieg2 \
    fog_coefficientRayleighR fog_coefficientRayleighG \
    fog_coefficientRayleighB fog_coefficientMieR \
    fog_coefficientMieG fog_coefficientMieB

screen.Fog_Densities=\
    FOG_RAIN_MULTIPLIER FOG_TOD_MULTIPLIER \
    CLOUDY_FOG_AMOUNT BASE_FOG_AMOUNT \
    ATMOSPHERIC_DENSITY Underwater_Fog_Density


screen.MATERIALS=\
    MAT_FORMAT <empty> \
    <empty> <empty> \
    [MAT_PARALLAX] [MAT_EMISSION] \
    [MAT_SPECULAR] MAT_POROSITY_INTEGRATED

screen.MAT_PARALLAX=\
    MAT_PARALLAX_ENABLED MAT_PARALLAX_DEPTH_WRITE \
    MAT_PARALLAX_DEPTH MAT_PARALLAX_ITERATIONS \
    MAT_PARALLAX_MAX_DIST MAT_PARALLAX_GENERATED

screen.MAT_EMISSION=\
    MAT_EMISSION_SCALE MAT_EMISSION_CURVE

screen.MAT_SPECULAR=\
    MAT_SPECULAR_ENABLED


screen.REFLECTIONS=\
    REFLECTION_ENABLED REFLECTION_ROUGH \
    REFLECTION_QUALITY REFLECTION_QUARTER_RES_DEPTH \
    sky_occlusion_threshold Roughness_Threshold \
    REFLECTION_ACCUMULATE REFLECTION_NEIGHBOR_CLAMP


screen.Shadows=\
    [Filtering] [SSGI_Parameters] \
    SCREENSPACE_CONTACT_SHADOWS shadowMapResolution \
    CLOUDS_SHADOWS CLOUDS_SHADOWS_STRENGTH \
    shadowDistanceRenderMul shadowDistance \
    SHADOW_FRUSTRUM_CULLING CAVE_LIGHT_LEAK_FIX \
    SHADOW_DISABLE_ALPHA_MIPMAPS Stochastic_Transparent_Shadows \
    SHADOW_COLORED


screen.Lighting=\
    [Torch] [Sky] \
    [Ambient]

screen.Torch=\
    TORCH_R TORCH_G \
    TORCH_B TORCH_AMOUNT

screen.Sky=\
    [Sky_coefficients] [Sun_and_Moon_Colors] \
    sunPathRotation

screen.Sky_coefficients=\
    Sky_Brightness sky_mieg \
    sky_coefficientRayleighR sky_coefficientRayleighG \
    sky_coefficientRayleighB sky_coefficientMieR \
    sky_coefficientMieG sky_coefficientMieB

screen.Sun_and_Moon_Colors=\
    sunColorR sunColorG \
    sunColorB sun_illuminance \
    moonColorR moonColorG \
    moonColorB moon_illuminance

screen.Ambient=\
    MIN_LIGHT_AMOUNT SEPARATE_AO \
    ambientOcclusionLevel Ambient_Mult


screen.Camera=\
    EXPOSURE_MULTIPLIER Exposure_Speed \
    AUTO_EXPOSURE Manual_exposure_value \
    BLOOM_STRENGTH BLOOM_QUALITY \
    FinalR FinalG \
    FinalB [Tonemapping] \
    [DepthOfField] [Purkinje_effect]

screen.Tonemapping=\
    TONEMAP USE_ACES_COLORSPACE_APPROXIMATION \
    SATURATION ACES_CG_ENABLED \
    CROSSTALK

screen.DepthOfField=\
    DOF HQ_DOF \
    HEXAGONAL_BOKEH AUTOFOCUS \
    focal aperture \
    MANUAL_FOCUS FAR_BLUR_ONLY \
    DoF_Adaptation_Speed

screen.Purkinje_effect=\
    Purkinje_strength Purkinje_strength \
    Purkinje_R Purkinje_G \
    Purkinje_B Purkinje_Multiplier


screen.Shading=\
    Texture_MipMap_Bias DISABLE_ALPHA_MIPMAPS \
    BICUBIC_UPSCALING CONTRAST_ADAPTATIVE_SHARPENING \
    SHARPENING

screen.Filtering=\
    Variable_Penumbra_Shadows VPS_Search_Samples \
    Min_Shadow_Filter_Radius Max_Shadow_Filter_Radius \
    Max_Filter_Depth SHADOW_FILTER_SAMPLE_COUNT

screen.SSGI_Parameters=\
    SSGI RAY_COUNT \
    STEPS STEP_LENGTH


screen.Wavy_stuff=\
    WAVY_STRENGTH WAVY_SPEED \
    WAVY_PLANTS


screen.Water_and_transparencies=\
    Dirt_Amount Dirt_Mie_Phase \
    rayMarchSampleCount \
    lightMapDepthEstimation Water_Top_Layer \
    <empty> [Advanced]

screen.Advanced=\
    Dirt_Scatter_R Dirt_Scatter_G \
    Dirt_Scatter_B Dirt_Absorb_R \
    Dirt_Absorb_G Dirt_Absorb_B \
    Water_Absorb_R Water_Absorb_G \
    Water_Absorb_B


screen.TAA_OPTIONS=\
    TAA_ENABLED TAA_RENDER_SCALE \
    TAA_BLEND_FACTOR TAA_CLOSEST_VELOCITY \
    TAA_NO_CLIP


sliders=\
    PHOTONICS_REFLECT_BOUNCES PHOTONICS_REFLECT_STEPS PHOTONICS_GI_BOUNCES PHOTONICS_GI_STEPS PHOTONICS_TINTING \
    MIN_LIGHT_AMOUNT TORCH_R TORCH_G TORCH_B TORCH_AMOUNT ambientOcclusionLevel Texture_MipMap_Bias \
    sun_illuminance sunColorG sunColorB sunColorR moon_illuminance moonColorR moonColorG moonColorB \
    MAT_PARALLAX_DEPTH MAT_PARALLAX_ITERATIONS MAT_PARALLAX_MAX_DIST \
    MAT_EMISSION_SCALE MAT_EMISSION_CURVE \
    WAVY_SPEED WAVY_STRENGTH \
    shadowDistance shadowDistanceRenderMul shadowMapResolution sunPathRotation SHADOW_FILTER_SAMPLE_COUNT CLOUDS_SHADOWS_STRENGTH VPS_Search_Samples Min_Shadow_Filter_Radius Max_Shadow_Filter_Radius \
    Underwater_Fog_Density Dirt_Mie_Phase Dirt_Amount Dirt_Scatter_R Dirt_Scatter_G Dirt_Scatter_B Dirt_Absorb_R Dirt_Absorb_G Dirt_Absorb_B Water_Absorb_R Water_Absorb_G Water_Absorb_B \
    REFLECTION_QUALITY \
    FinalR FinalG FinalB Purkinje_strength Purkinje_strength Purkinje_R Purkinje_G Purkinje_B DoF_Adaptation_Speed Purkinje_Multiplier CROSSTALK SHARPENING SATURATION Exposure_Speed Manual_exposure_value focal aperture MANUAL_FOCUS EXPOSURE_MULTIPLIER \
    TAA_RENDER_SCALE TAA_BLEND_FACTOR \
    BLOOMY_FOG FOG_RAIN_MULTIPLIER FOG_TOD_MULTIPLIER CLOUDY_FOG_AMOUNT BASE_FOG_AMOUNT ANTI_GHOSTING BLOOM_STRENGTH Ambient_Mult Sky_Brightness fog_coefficientMieR fog_coefficientMieG fog_coefficientMieB sky_mieg sky_coefficientMieB sky_coefficientMieG sky_coefficientMieR sky_coefficientRayleighB sky_coefficientRayleighG sky_coefficientRayleighR CLOUDS_QUALITY SKY_BRIGHTNESS_DAY SKY_BRIGHTNESS_NIGHT FLICKER_REDUCTION MOTION_REJECTION VL_SAMPLES SEA_LEVEL ATMOSPHERIC_DENSITY fog_mieg1 fog_mieg2 fog_coefficientRayleighR fog_coefficientRayleighG Max_Filter_Depth SSAO_SAMPLES Water_Top_Layer fog_coefficientRayleighB rayMarchSampleCount VL_RENDER_RESOLUTION BLOOM_QUALITY VL_RENDER_RESOLUTION RAY_COUNT STEPS STEP_LENGTH cloud_LevelOfDetail cloud_ShadowLevelOfDetail cloud_LevelOfDetailLQ cloud_ShadowLevelOfDetailLQ minRayMarchSteps maxRayMarchSteps minRayMarchStepsLQ maxRayMarchStepsLQ cloudDensity cloudCoverage fbmAmount fbmPower1 fbmPower2 cloudMieG cloudMieG2 cloudMie2Multiplier


texture.noise=texture/noises.png
#texture.composite.colortex6=texture/blueNoise.png

customTexture.texBlueNoise=/texture/blueNoise.png
customTexture.texWave=/texture/wave.png

#ifdef PH_ENABLE_GI
#    image.imgPhotonicsIndirect=texPhotonicsIndirect RGB RGBA16F HALF_FLOAT false true 1.00 1.00
#endif

blend.gbuffers_terrain=off
blend.gbuffers_textured= SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_armor_glint= SRC_ALPHA ZERO ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_textured_lit= SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_weather= SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_water= ONE ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_hand_water= SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_entities_translucent= ONE ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_entities=off
blend.gbuffers_hand=off
blend.gbuffers_block=off
blend.gbuffers_basic=off
blend.gbuffers_damagedblock=SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.gbuffers_skytextured=off

#alphaTest.gbuffers_entities=GREATER 0.1
alphaTest.gbuffers_weather=false
alphaTest.gbuffers_water=false
alphaTest.gbuffers_skybasic=false
alphaTest.gbuffers_skytextured=false


#ifdef REFLECTION_QUARTER_RES_DEPTH
    image.imgDepthQ=texDepthQ RED R16F HALF_FLOAT false true 0.25 0.25
#else
    program.deferred2.enabled=false
#endif

#if !defined(PHOTONICS) || !defined(PHOTONICS_REFLECT_ENABLED)
    program.composite3.enabled=false
#endif

#if !(defined(PHOTONICS) && defined(PHOTONICS_REFLECT_ENABLED) && defined(REFLECTION_ROUGH) && (defined(REFLECTION_ACCUMULATE) || defined(REFLECTION_NEIGHBOR_CLAMP)))
    program.composite4.enabled=false
#endif

#if TAA_RENDER_SCALE == 100
    program.composite7.enabled=false
#else
    image.imgTAA_min=texTAA_min RGB RGBA16F HALF_FLOAT false true 1.00 1.00
    image.imgTAA_max=texTAA_max RGB RGBA16F HALF_FLOAT false true 1.00 1.00
#endif


# CUSTOM UNIFORMS

variable.float.texelSizeX = 1.0/viewWidth
variable.float.texelSizeY = 1.0/viewHeight
uniform.vec2.texelSize=vec2(texelSizeX,texelSizeY)

uniform.int.framemod8 = frameCounter%8

variable.float.normSunVec = sqrt(sunPosition.x*sunPosition.x+sunPosition.y*sunPosition.y+sunPosition.z*sunPosition.z)
variable.float.normUpVec = sqrt(upPosition.x*upPosition.x+upPosition.y*upPosition.y+upPosition.z*upPosition.z)

variable.float.sunPosX = sunPosition.x/normSunVec
variable.float.sunPosY = sunPosition.y/normSunVec
variable.float.sunPosZ = sunPosition.z/normSunVec

uniform.vec3.sunVec=vec3(sunPosX,sunPosY,sunPosZ)

variable.float.upPosX = upPosition.x/normUpVec
variable.float.upPosY = upPosition.y/normUpVec
variable.float.upPosZ = upPosition.z/normUpVec

uniform.vec3.upVec=vec3(upPosX,upPosY,upPosZ)
uniform.float.sunElevation = sunPosX*upPosX+sunPosY*upPosY+sunPosZ*upPosZ
uniform.float.lightSign = clamp(sunElevation * 1000000000000000000, 0.0, 1.0) * 2.0 - 1.0

#Max angle at frustrum diagonal
variable.float.maxAngle = atan(1.0 / gbufferProjection.1.1 * sqrt(1.0+(aspectRatio * aspectRatio)))
uniform.float.cosFov = cos(maxAngle)
variable.float.viewDirX = gbufferModelViewInverse.2.0
variable.float.viewDirY = gbufferModelViewInverse.2.1
variable.float.viewDirZ = gbufferModelViewInverse.2.2
variable.float.normView = sqrt(viewDirX*viewDirX + viewDirY*viewDirY + viewDirZ*viewDirZ)
variable.float.shViewDirX = (shadowModelView.0.0 * viewDirX + shadowModelView.1.0 * viewDirY + shadowModelView.2.0 * viewDirZ)/normView
variable.float.shViewDirY = (shadowModelView.0.1 * viewDirX + shadowModelView.1.1 * viewDirY + shadowModelView.2.1 * viewDirZ)/normView
variable.float.shViewDirZ = (shadowModelView.0.2 * viewDirX + shadowModelView.1.2 * viewDirY + shadowModelView.2.2 * viewDirZ)/normView

uniform.vec3.shadowViewDir = vec3(shViewDirX, shViewDirY, shViewDirZ)

variable.float.shStartX = (shadowModelView.0.0 * gbufferModelViewInverse.3.0 + shadowModelView.1.0 * gbufferModelViewInverse.3.1 + shadowModelView.2.0 * gbufferModelViewInverse.3.2)
variable.float.shStartY = (shadowModelView.0.1 * gbufferModelViewInverse.3.0 + shadowModelView.1.1 * gbufferModelViewInverse.3.1 + shadowModelView.2.1 * gbufferModelViewInverse.3.2)
variable.float.shStartZ = (shadowModelView.0.2 * gbufferModelViewInverse.3.0 + shadowModelView.1.2 * gbufferModelViewInverse.3.1 + shadowModelView.2.2 * gbufferModelViewInverse.3.2)

uniform.vec3.shadowCamera = vec3(shStartX + shadowModelView.3.0 + shViewDirX*2., shStartY + shadowModelView.3.1 + shViewDirY*2., shStartZ + shadowModelView.3.2 + shViewDirZ*2.0)


variable.float.wSunX = (gbufferModelViewInverse.0.0 * sunPosX + gbufferModelViewInverse.1.0 * sunPosY + gbufferModelViewInverse.2.0 * sunPosZ)
variable.float.wSunY = (gbufferModelViewInverse.0.1 * sunPosX + gbufferModelViewInverse.1.1 * sunPosY + gbufferModelViewInverse.2.1 * sunPosZ)
variable.float.wSunZ = (gbufferModelViewInverse.0.2 * sunPosX + gbufferModelViewInverse.1.2 * sunPosY + gbufferModelViewInverse.2.2 * sunPosZ)

variable.float.shSunX = (shadowModelView.0.0 * wSunX + shadowModelView.1.0 * wSunY + shadowModelView.2.0 * wSunZ)
variable.float.shSunY = (shadowModelView.0.1 * wSunX + shadowModelView.1.1 * wSunY + shadowModelView.2.1 * wSunZ)
variable.float.shSunZ = (shadowModelView.0.2 * wSunX + shadowModelView.1.2 * wSunY + shadowModelView.2.2 * wSunZ)

uniform.vec3.shadowLightVec = vec3(lightSign*shSunX, lightSign*shSunY, lightSign*shSunZ)

uniform.float.shadowMaxProj = 150.0/abs(sunPosY)
uniform.float.waveScale = if(in(biome_category,CAT_OCEAN,CAT_BEACH), 1.0, 0.0)*74.0+54.0
